var accelBlob = (function(){
  var bin=atob("gC7+AIAu8QHILgAugC78AIAu+wCALv8AgC79AIAuQrBQOSEusPAQMCEuFvCALvIBXVBbUgFCO4BBMAFCPIAALgFAAUIhLv+vuC4Dt4AuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAAAAAAAAAAQBAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJguhAEgJpgu9wAQMCEuWfCYLq4AmC6rs5guurMALgAu0C6YLtQBAS5aAACyEC8AMCEuWgBBUJguALBBUJgu8rBBUENSmC7Vs0FQRVKYLtWzmC6uAOMtAS5V8MAuIS5V8DBQADBHVgUwBSz7fz6+0rqyuWwLUw75L1MaAS9NDvUv0n8EMB8s4X/FAaMDcg4DL3IaDy95Dw0v4W9PBF+5sb/6C9JvlgaxJVG/638GALIlJwPbf8+/Pr8BuNK6QbqyuQcKbgvAkN8vQJHdL/tv0F+4LhBQ+38hJZguZQH7byEl8F8QJYAuswAAMcAuIS668MguyC7ILsguyC6qAAUAqgAFAC0B1Hs7Adt6BAA/e81swwSFCcME7OYMRgEAJwAZAJYAoAABAAwA8DwAAQEAAwABAA4AAABOFIgAVwBxAHoAAED/fwCArwD/AP+3AAIAsAWAsfCAAF7wwABZ8InwWgAAIFwAUABUAFsA//tS8FbwMwkzBwAIkAEA+AABAgGUAd0DwK0LL8CoAy/AkAcvgKYFL0CpEi9AkQEvAKsOL8CsADBLUgcvwKkDL8CRAy+ApwEvQKEFL8AuFyUGJcAu8D9JUrgug4YBMAAwlEAkGAYAUw5PAvkvuC6AqAMlEC+AkAEvQQ4ML/M/GAUFMF0HFQ4DL1UaAi/MDwAvWAQBJbguuC5ZUEEwAkBRCgFCGIJNUGBCcDxPVEJCaYKCMkNAGAgCCkBCQoACPwFAEFBKCPt/EUILMQtCPoABMgFCAC4BLkDwEZAgLwMwU1BRVAQ1BjBXUlUyHRrjIhgaVVjjIgQw1UC1DeG+b7uAkakNAYm1IxCh9y/aDgQ16y8BLiUAcBoAMCEwAiwIIjAwALIGLyEuWfCYLq4AAC4ALtAu+2/wX7guYVAFLgDwW1bTDwFA9DPMCA0v9DCUCLmIAqMEL19YTAqHogUsyyJbVEoK8jvKCDyAJy5Z8AFAAUK4LsguGiQmAIAugwCALhgAgC4YAIAuGACALhgAgC4YAHBQAy4fAfF/KiW5guB/238AMEUwMjADMAQw9m/yCfwTwqu1CccjgLPmb7cBAC6LQUtCBS/FfwUwRkCuBcVvRkIBgCO9074DiUGC3wwDouQv4G+RbxFCw7KhbxFCAC6xbwFCBi8AMgMuWfAICiEuWfAGLfE9AS5Z8AEIIS5Z8NtvkF+4LmBQw3/Uf+d/9n+yf6V/NjAHLgHwvr2+u2NYdwVBVmVUJ0EGQfi/vgu1EdZCA4laDvYvEjAlLloAAjElLrjw1G/Db+dvsm+lb/ZvoF/ILnBQQo7Uf/Z/RyUaGGdS8QBkJQEwOQKUQYFB4n++u72NAr21f461ugrGf6t/USWYLkIB1W/ibyoYZ1SyAQIwxG96AxJBdCXQf1K800Fuut62IAvHf5F/mC5CAfJv1W/KFlUY3RiVb+oYZ1oxJXUBATAgJTkCXrqCvI62IQuYLkIB4m+1byoY4H/xfwQwZ1TyAHwChW/Qbw0XaBjgGJBvxG/FGOtvsgEbQwIwegP7bz2PC0M+uhK9Urxuu6IKnrXetjAL93+YLkIB9W8xJdFvkm+rb1BDQ0OQX0lWgC5vARBQA0AZGEtWGQU2Jfd/ShdUGOwYCRcBMAwH4hjeAPJvlwJHWNwAkQK/uCG9igrALgJC8F8JLh0BBS4dAaO8RL6QUE+5By4dAUoln7g5j7K98n+/uet/igo3iQswkwqLf8tDC0OAstN/wX+QLp2xICUBLlYAAZAOL2lSAS5TALR/on+YLqOxADAhLlYAwW/Tb6JvtG8LMAEuHQEGvAa7VyUBLh0BlLEFvLZ/D7ttUICzDy8NLh0BcV63CS0uHQFzXGtem0ObQ9tDm0MbQstDC0KLQ0CyBS9rUAAuFkALQHZ/i3/LCgEuUwBpUm9cmC7vsZBvALILL/BvALIIL2tYbVASQRJCITAEQQRCIy5e8MBvALImL3RvgG9zVIi9yLhLCpRCkUKQQoi6a1Lzb1RChULAkEBCFS9tUgAuUkBBQKIEQQZAqgQvQJALL7FvSg8IL7JvgLIFL21UITCUQoBCIy5e8NBvALITLwEuUgAJLlsABBoNL3VQKS5SACRCRDACQAJCCYAALgRCAy0QMCEuVgDrb3BfuC4JhkdU5EDDgJQEw0ATBQVAJQWKF3MwcwmMF/MI4wBMghUBs7VTQosWQ7ZSQkwXVEJVQlNCUkJUQkVCbYJ3VFJCEFB5VFJC+38iMHtWQ0JEggswUkJbQnyES0I1gpCAi0ILQjWABDALQjeAFTBgJZgu4rGLg/tvZULALkRC8F8FgAIwUYICQhMwQUBLCH1UPoBRFMAuAUIALkBR0X8SJQIwQkMyMIJDxn/lf7R/o3+Qf4t/mC7sAMB+AKwBL0lQwH4ALpBvCYrRb3V/TIJjQWV/EX8ALmRBRIVSf0V/AC6mQIBAMn+CjsJuRUHwfyd/An+YLmmwI2/Rb8JA+YYjf4Cy4H4PLzJvZG+CQPJ/UIJCb1Bvc2+FQMNABEEGQOJumC5psOB+8zEQbzaA4W4CQHF/UQQCMECokQRKIokWkwhKAJW0CRiOFhMwkwghb2B/TYYCgLIAQUAhtVB/Q3+YLtiwQG9ib1VvE0CEQAFARUFCvh0YTAQxDwSKwG8RMAIvAC4DLAFCIzADQgAu1m9EQYqHdosAs1N/FS8Eb39ei43nAcClhEEBLwChAy/ArQgvAKUGL8ZAgY0HMDwF1kIELMRCAiwHMAcwhoaUb9d+Do0AQHSJx0ACsvkpRUGGQb6AIUF1I4JAx0JFfzR/IH+YLtiwMW9gbyRvIkAFQUNAEwFDhqwP0W8wfwAvREJIikGI4UATfwR/9X6YLtiwEW9gbzRvQkADQJoEBEFDgqIOA28AL8JCAC5BQHJvmC7YsCVvcm9TQZMO0W9GgBswAzAMLwRAAJFCQggv9m5Eb4ZBtA4DLwKI234DQwtCRo1EQUeABW+UD3Z/YH8CL0WJQkMDQ0mIpW9AkaR/FTDib9NuAy8EMINCgC6TswRAJSkEQoNCRYKUbwSFwLKQLn+zFYc8jMRARn/ChgdAhkH0vwCzDC+QbxaARiUAQFclBBiuDhAwBjB1JUYjYG9kJcRA+oYAszN/CS+Tb9iIU28EQcNA3A4TMAQw3CKzJUCzAi87JcCQBS+Rb9BvmC7isU0sBDCNiENAgkBUf9oPBDAIL8GAQELCDwIvADDAfhstwH4ZLeG8km9PBJCEQKghBYNATCJLDraEITACLxEwBCzBfuNvwX7BQgAuAECBQAS9QG+YLtiwUG8RMAJAUQjDbgOAmRULQLFv0G+2f1t/BDBPVAMwESwUgFVvBkB1AVi7agkFQsGGR0BRJb4BVkMALkZB9AO2b0dDXg7tLzFvYG9CQBUwAoKVCARCUkICLERCBDA+jpFvT4wCQINBtY2TDtBvAS+YLuKxAC7AQYFBwQ/AbwEvBEIALnBvPIIAQEFAiRaVCEoABLyRtAEO4G8HL6FvAC5BQECyAi+hbwVCREIALotvwF64LhBQgVJDUPt/mC7Js0NSRYIQMFBCYDD7b8AuQELwXxBQg1JFUPt/mC7Js0VSRYIAMFBCcDD7b8AuQELwXxIwEkICMBJCEkISQgJCA4BBhBFCAkK4LkiEvoqEQHBQAkEtu2NBQoRFQcJ/tX+As+Z/0H/zfxIwXi8xJVVAQZGhfw8vATDBQgAuwm8TQJNCAC4TQJNCAC4AQIBCvYDALgFCkF/HhgEwxUD7hkVBBEFDvsO71b5Vupd/BTDRFfcJwLMJLwZAx0C3BQcwgKn+BbcjdA9VI+ZvQYIBgMGGQ6LsL7BvpG8oGtFvw28CLwIwGCwCQwVBaimWbwVDbg4QL/RvALMDLz+JlBQlLl7wQSUjJRVBlUIALhVBlUIALgRBhEIAkAkvUEDQQgAuUEDQQgAuQEACLMBCQkKQX7gugC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAgC4YAIAuGACALhgAAUt7RBhccEf65///T/TAUHBHAAA=");
  return {
    getSize:E.nativeCall(6157, "int()", bin),
    getValue:E.nativeCall(6145, "int(int)", bin),
  };
})();

var ACCELPIN =D16;

function delayms(d) {var t = getTime()+d/1000; while(getTime()<t);}

var ACCEL = {
    writeByte:(a,d) => { 
      wOSI2C.writeTo(0x18,a,d);
    }, 
    readBytes:(a,n) => {
      wOSI2C.writeTo(0x18, a);
        return wOSI2C.readFrom(0x18,n); 
    },
    writeblob:()=>{
      var len = accelBlob.getSize();
      var buf = new Int8Array(16);
      for (var i = 0; i < len; i += 16) {
        ACCEL.writeByte(0x5B, (i/2) & 0x0F);
        ACCEL.writeByte(0x5C, (i/2) >> 4);
        for (var j = 0; j<16; ++j) buf[j] = accelBlob.getValue(i+j);
        ACCEL.writeByte(0x5E,buf);
      }
    },
    init:() => {
        ACCEL.writeByte(0x7E, 0xB6);
        delayms(10);
        ACCEL.writeByte(0x7C, 0x00);
        delayms(1);
        ACCEL.writeByte(0x59, 0x00);
        ACCEL.writeblob();
        ACCEL.writeByte(0x59, 0x01);
        delayms(10);
        ACCEL.writeByte(0x7D, 0x04);
        ACCEL.writeByte(0x41, 0x00); // 2g range
        ACCEL.writeByte(0x40, 0x17); 
        ACCEL.writeByte(0x7C, 0x03);
        return ACCEL.readBytes(0x0,1)[0];
    },
    read:()=>{
      function conv(lo,hi) { 
        var i = (hi<<8)+lo;
        return ((i & 0x7FFF) - (i & 0x8000))/16;
      }
      var a = ACCEL.readBytes(0x12,6);
      return {x:conv(a[0],a[1]), y:conv(a[2],a[3]), z:conv(a[4],a[5])};
  },
};

ACCEL.configRead= function(len,offset){
  ACCEL.writeByte(0x7C, 0x00); //disable sleep mode
  delayms(1);
  var res = [];
  for (var i = 0; i < len; i += 16) {
    ACCEL.writeByte(0x5B, (offset + (i/2)) & 0x0F);
    ACCEL.writeByte(0x5C, (offset + (i/2)) >> 4);
    res.push(ACCEL.readBytes(0x5E, (len-i >= 16) ? 16 : (len - i)));
  }
  ACCEL.writeByte(0x7C, 0x00); //enable sleep mode
  return res;
}

ACCEL.configWrite=function(data,offset){
  ACCEL.writeByte(0x7C, 0x00); //disable sleep mode
  delayms(1);
  for (var j =0; j<data.length;++j) {
    var i = j*16;
    ACCEL.writeByte(0x5B, (offset + (i/2)) & 0x0F);
    ACCEL.writeByte(0x5C, (offset + (i/2)) >> 4);
    ACCEL.writeByte(0x5E,data[j]);
  }
  ACCEL.writeByte(0x7C, 0x00); //enable sleep mode
}

E.stepInit = function(){
  var feature = ACCEL.configRead(0x46,256);
  feature[3][11] = 0x34; // 0x3A+1
  ACCEL.configWrite(feature,256);
}

E.totalSteps = function(){
  var res = ACCEL.readBytes(0x1E,4);
  return (res[3]<<24)+(res[2]<<16)+(res[1]<<8)+res[0];
}



  